# Generated by Django 3.2.18 on 2023-04-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/images/default_profile_ua3v6g', upload_to='images/'),
        ),
    ]
