# Generated by Django 3.2.18 on 2023-04-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
