# Generated by Django 3.2.18 on 2023-04-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20230416_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
