# Generated by Django 3.2.18 on 2023-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_alter_meetups_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
