# Generated by Django 3.2.18 on 2023-04-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_alter_meetups_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
